# Generated by Django 3.2.10 on 2022-02-17 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('model_detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('interface', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'model_record',
                'abstract': False,
                'managed': True,
            },
        ),
    ]
