# Generated by Django 3.2.10 on 2022-02-17 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_detection', '0002_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='create_time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='record',
            name='deleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='record',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='record',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
