# Generated by Django 3.2.10 on 2022-02-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_detection', '0003_auto_20220217_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='source',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='record',
            name='interface',
            field=models.CharField(max_length=128),
        ),
    ]
